# Generated by Django 3.1.7 on 2021-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='phone',
            field=models.FloatField(max_length=11, null=True),
        ),
    ]
